import type { Metadata } from 'next'
import { Galindo, Geist, Geist_Mono, Montserrat } from 'next/font/google'
import './globals.css'
import { galindo, montserrat } from './fonts'
import { ThemeProvider } from '@/components/theme-provider'
import { ThemeToggle } from '@/components/theme-toggle'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${galindo.variable} ${montserrat.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="my-8 flex justify-between items-center px-8">
            <h1 className="text-4xl font-bold text-center font-galindo">
              PuzzleHub
            </h1>
            <ThemeToggle />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
