name: CI
concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
        - uses: actions/checkout@v4

        - uses: opentofu/setup-opentofu@v1
          with:
            tofu_version: 1.9.0

        - uses: pnpm/action-setup@v4

        - uses: actions/setup-node@v4
          with:
            node-version-file: .node-version
            cache: pnpm

        - run: pnpm install
        - run: pnpm run lint
